package com.vic.mybatis.demo.model;

public class TLogs {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_logs.id
     *
     * @mbggenerated Sat Apr 27 19:17:25 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_logs.action
     *
     * @mbggenerated Sat Apr 27 19:17:25 CST 2019
     */
    private String action;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_logs.data
     *
     * @mbggenerated Sat Apr 27 19:17:25 CST 2019
     */
    private String data;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_logs.authorId
     *
     * @mbggenerated Sat Apr 27 19:17:25 CST 2019
     */
    private Integer authorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_logs.ip
     *
     * @mbggenerated Sat Apr 27 19:17:25 CST 2019
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_logs.created
     *
     * @mbggenerated Sat Apr 27 19:17:25 CST 2019
     */
    private Integer created;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_logs.id
     *
     * @return the value of t_logs.id
     *
     * @mbggenerated Sat Apr 27 19:17:25 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_logs.id
     *
     * @param id the value for t_logs.id
     *
     * @mbggenerated Sat Apr 27 19:17:25 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_logs.action
     *
     * @return the value of t_logs.action
     *
     * @mbggenerated Sat Apr 27 19:17:25 CST 2019
     */
    public String getAction() {
        return action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_logs.action
     *
     * @param action the value for t_logs.action
     *
     * @mbggenerated Sat Apr 27 19:17:25 CST 2019
     */
    public void setAction(String action) {
        this.action = action == null ? null : action.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_logs.data
     *
     * @return the value of t_logs.data
     *
     * @mbggenerated Sat Apr 27 19:17:25 CST 2019
     */
    public String getData() {
        return data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_logs.data
     *
     * @param data the value for t_logs.data
     *
     * @mbggenerated Sat Apr 27 19:17:25 CST 2019
     */
    public void setData(String data) {
        this.data = data == null ? null : data.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_logs.authorId
     *
     * @return the value of t_logs.authorId
     *
     * @mbggenerated Sat Apr 27 19:17:25 CST 2019
     */
    public Integer getAuthorid() {
        return authorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_logs.authorId
     *
     * @param authorid the value for t_logs.authorId
     *
     * @mbggenerated Sat Apr 27 19:17:25 CST 2019
     */
    public void setAuthorid(Integer authorid) {
        this.authorid = authorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_logs.ip
     *
     * @return the value of t_logs.ip
     *
     * @mbggenerated Sat Apr 27 19:17:25 CST 2019
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_logs.ip
     *
     * @param ip the value for t_logs.ip
     *
     * @mbggenerated Sat Apr 27 19:17:25 CST 2019
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_logs.created
     *
     * @return the value of t_logs.created
     *
     * @mbggenerated Sat Apr 27 19:17:25 CST 2019
     */
    public Integer getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_logs.created
     *
     * @param created the value for t_logs.created
     *
     * @mbggenerated Sat Apr 27 19:17:25 CST 2019
     */
    public void setCreated(Integer created) {
        this.created = created;
    }
}