package com.vic.mybatis.demo.model;

public class TUsers {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.uid
     *
     * @mbggenerated Sat Apr 27 19:17:25 CST 2019
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.username
     *
     * @mbggenerated Sat Apr 27 19:17:25 CST 2019
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.password
     *
     * @mbggenerated Sat Apr 27 19:17:25 CST 2019
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.email
     *
     * @mbggenerated Sat Apr 27 19:17:25 CST 2019
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.homeUrl
     *
     * @mbggenerated Sat Apr 27 19:17:25 CST 2019
     */
    private String homeurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.screenName
     *
     * @mbggenerated Sat Apr 27 19:17:25 CST 2019
     */
    private String screenname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.created
     *
     * @mbggenerated Sat Apr 27 19:17:25 CST 2019
     */
    private Integer created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.activated
     *
     * @mbggenerated Sat Apr 27 19:17:25 CST 2019
     */
    private Integer activated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.logged
     *
     * @mbggenerated Sat Apr 27 19:17:25 CST 2019
     */
    private Integer logged;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.groupName
     *
     * @mbggenerated Sat Apr 27 19:17:25 CST 2019
     */
    private String groupname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.uid
     *
     * @return the value of t_users.uid
     *
     * @mbggenerated Sat Apr 27 19:17:25 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.uid
     *
     * @param uid the value for t_users.uid
     *
     * @mbggenerated Sat Apr 27 19:17:25 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.username
     *
     * @return the value of t_users.username
     *
     * @mbggenerated Sat Apr 27 19:17:25 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.username
     *
     * @param username the value for t_users.username
     *
     * @mbggenerated Sat Apr 27 19:17:25 CST 2019
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.password
     *
     * @return the value of t_users.password
     *
     * @mbggenerated Sat Apr 27 19:17:25 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.password
     *
     * @param password the value for t_users.password
     *
     * @mbggenerated Sat Apr 27 19:17:25 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.email
     *
     * @return the value of t_users.email
     *
     * @mbggenerated Sat Apr 27 19:17:25 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.email
     *
     * @param email the value for t_users.email
     *
     * @mbggenerated Sat Apr 27 19:17:25 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.homeUrl
     *
     * @return the value of t_users.homeUrl
     *
     * @mbggenerated Sat Apr 27 19:17:25 CST 2019
     */
    public String getHomeurl() {
        return homeurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.homeUrl
     *
     * @param homeurl the value for t_users.homeUrl
     *
     * @mbggenerated Sat Apr 27 19:17:25 CST 2019
     */
    public void setHomeurl(String homeurl) {
        this.homeurl = homeurl == null ? null : homeurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.screenName
     *
     * @return the value of t_users.screenName
     *
     * @mbggenerated Sat Apr 27 19:17:25 CST 2019
     */
    public String getScreenname() {
        return screenname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.screenName
     *
     * @param screenname the value for t_users.screenName
     *
     * @mbggenerated Sat Apr 27 19:17:25 CST 2019
     */
    public void setScreenname(String screenname) {
        this.screenname = screenname == null ? null : screenname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.created
     *
     * @return the value of t_users.created
     *
     * @mbggenerated Sat Apr 27 19:17:25 CST 2019
     */
    public Integer getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.created
     *
     * @param created the value for t_users.created
     *
     * @mbggenerated Sat Apr 27 19:17:25 CST 2019
     */
    public void setCreated(Integer created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.activated
     *
     * @return the value of t_users.activated
     *
     * @mbggenerated Sat Apr 27 19:17:25 CST 2019
     */
    public Integer getActivated() {
        return activated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.activated
     *
     * @param activated the value for t_users.activated
     *
     * @mbggenerated Sat Apr 27 19:17:25 CST 2019
     */
    public void setActivated(Integer activated) {
        this.activated = activated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.logged
     *
     * @return the value of t_users.logged
     *
     * @mbggenerated Sat Apr 27 19:17:25 CST 2019
     */
    public Integer getLogged() {
        return logged;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.logged
     *
     * @param logged the value for t_users.logged
     *
     * @mbggenerated Sat Apr 27 19:17:25 CST 2019
     */
    public void setLogged(Integer logged) {
        this.logged = logged;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.groupName
     *
     * @return the value of t_users.groupName
     *
     * @mbggenerated Sat Apr 27 19:17:25 CST 2019
     */
    public String getGroupname() {
        return groupname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.groupName
     *
     * @param groupname the value for t_users.groupName
     *
     * @mbggenerated Sat Apr 27 19:17:25 CST 2019
     */
    public void setGroupname(String groupname) {
        this.groupname = groupname == null ? null : groupname.trim();
    }
}