package com.vic.mybatis.demo.mapper;


import com.vic.mybatis.demo.model.TLogs;
import com.vic.mybatis.demo.model.TLogsExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface TLogsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_logs
     *
     * @mbggenerated Sat Apr 27 19:17:25 CST 2019
     */
    int countByExample(TLogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_logs
     *
     * @mbggenerated Sat Apr 27 19:17:25 CST 2019
     */
    int deleteByExample(TLogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_logs
     *
     * @mbggenerated Sat Apr 27 19:17:25 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_logs
     *
     * @mbggenerated Sat Apr 27 19:17:25 CST 2019
     */
    int insert(TLogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_logs
     *
     * @mbggenerated Sat Apr 27 19:17:25 CST 2019
     */
    int insertSelective(TLogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_logs
     *
     * @mbggenerated Sat Apr 27 19:17:25 CST 2019
     */
    List<TLogs> selectByExample(TLogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_logs
     *
     * @mbggenerated Sat Apr 27 19:17:25 CST 2019
     */
    TLogs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_logs
     *
     * @mbggenerated Sat Apr 27 19:17:25 CST 2019
     */
    int updateByExampleSelective(@Param("record") TLogs record, @Param("example") TLogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_logs
     *
     * @mbggenerated Sat Apr 27 19:17:25 CST 2019
     */
    int updateByExample(@Param("record") TLogs record, @Param("example") TLogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_logs
     *
     * @mbggenerated Sat Apr 27 19:17:25 CST 2019
     */
    int updateByPrimaryKeySelective(TLogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_logs
     *
     * @mbggenerated Sat Apr 27 19:17:25 CST 2019
     */
    int updateByPrimaryKey(TLogs record);
}