package com.vic.mybatis.demo.mapper;


import com.vic.mybatis.demo.model.TUsers;
import com.vic.mybatis.demo.model.TUsersExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface TUsersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_users
     *
     * @mbggenerated Sat Apr 27 19:17:25 CST 2019
     */
    int countByExample(TUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_users
     *
     * @mbggenerated Sat Apr 27 19:17:25 CST 2019
     */
    int deleteByExample(TUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_users
     *
     * @mbggenerated Sat Apr 27 19:17:25 CST 2019
     */
    int deleteByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_users
     *
     * @mbggenerated Sat Apr 27 19:17:25 CST 2019
     */
    int insert(TUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_users
     *
     * @mbggenerated Sat Apr 27 19:17:25 CST 2019
     */
    int insertSelective(TUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_users
     *
     * @mbggenerated Sat Apr 27 19:17:25 CST 2019
     */
    List<TUsers> selectByExample(TUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_users
     *
     * @mbggenerated Sat Apr 27 19:17:25 CST 2019
     */
    TUsers selectByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_users
     *
     * @mbggenerated Sat Apr 27 19:17:25 CST 2019
     */
    int updateByExampleSelective(@Param("record") TUsers record, @Param("example") TUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_users
     *
     * @mbggenerated Sat Apr 27 19:17:25 CST 2019
     */
    int updateByExample(@Param("record") TUsers record, @Param("example") TUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_users
     *
     * @mbggenerated Sat Apr 27 19:17:25 CST 2019
     */
    int updateByPrimaryKeySelective(TUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_users
     *
     * @mbggenerated Sat Apr 27 19:17:25 CST 2019
     */
    int updateByPrimaryKey(TUsers record);
}